#/bin/bash
rm *.ic0
rm *.st0
rm *.tr0
rm *.tr0.lis
rm *.csv
rm *.pa0
# converts a verilog netlist to a spice
# change the input netlist name (ex. boothR2_serial_alu_unit_synth.v) and possibly the output netlist name (saed90nm.cdl) for running
# different designs 

# -p and -n are the names of the pmos and nmos transistors. Probably won't need to change rn 
# -m is the spice model, currently hardcoded in script. -o is the name I want to give to the generated output file
python3 new_v2s.py -i boothR2_serial_alu_synth.v -l saed90nm.cdl -p P12 -n N12 -m ../spice_models/ptm_22nm_bulk_hp.l -o boothflow.sp
echo Please go and change the libraries mentioned in boothflow.sp
read
# echo Please go and set Wn and Wp to 45n in minlib.sp
# read


# when doing the conversions, will need to run sims on and get the output time files like I generated for Nathan
# earlier in the semester and replace the file listed after -i.
# change -d to match the name of the subcircuit/module you are testing in the verilog/spice netlist
# -c is the spice file containing the subcircuit. Match with -o from new_v2s.py
python3 generateTBInput.py -i Booth_alu_times.txt -m ../spice_models/ptm_22nm_bulk_hp.l -d boothR2_serial_alu -c boothflow.sp
#the testbench.json file is auto generated by the python script above
python3 generateTestbench.py -i testbench.json -o testbench.sp
# > *name* prints the output to the file rather than the terminal. Need it to be stored in a file to process
hspice testbench.sp > hspice_raw_output_boothflow.txt


# make -i match the file in the line above (the name after the >). The after > can be whatever I want, just keep names organized
# -o can be named whatever i want. That is what will finally be used to check the behavior
python3 process_output.py -i hspice_raw_output_boothflow.txt -o hspice_processed_output_boothflow.txt
#cleanup temp files
rm temp_translation.json
rm temp.json