def gen_boothR2_serial_alu(spice_filename, circuit_name, numberofsrams):
	spice_file = open(spice_filename,'a')
	spice_file.write('.SUBCKT boothR2_serial_alu op_bus0_ op_bus1_ clk x y ce reset out n_vdd n_gnd')
	spice_file.write("\n")
	spice_file.write('Xcb_reg_reg clk n35 n71 n36 n_vdd n_gnd dff')
	spice_file.write("\n")
	spice_file.write('XU37 n37 n38 out n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU38 n39 n40 n38 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU39 n41 n42 n40 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU40 n43 n71 n42 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU41 n44 n43 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU42 n44 n36 n41 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU43 n45 n46 n44 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU44 y n47 n46 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU45 x n48 n45 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU46 y n48 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU47 n49 n50 n37 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU48 n51 n52 n50 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU49 x n53 n52 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU50 op_bus0_ n54 n49 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU51 y op_bus1_ n54 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU52 reset n55 n35 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU53 n56 n57 n55 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU54 n58 n36 n57 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU55 n59 n60 n58 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU56 ce n61 n60 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU57 n39 y n61 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU58 n62 n39 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU59 n63 n64 n62 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU60 op_bus1_ n51 n64 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU61 op_bus0_ n53 n63 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU62 n65 n66 n56 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU63 y n59 n66 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU64 n67 n68 n59 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU65 n69 n53 n68 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU66 op_bus1_ n53 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU67 op_bus0_ n47 n69 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU68 x n47 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU69 n70 op_bus1_ n67 n_vdd n_gnd nand2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU70 x n51 n70 n_vdd n_gnd nor2_decode')
	spice_file.write("Wn=45n Wp=55n \n")
	spice_file.write('XU71 op_bus0_ n51 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('XU72 ce n65 n_vdd n_gnd inv')
	spice_file.write("Wn=boothr2_serial_alu_inv_pmos+3 Wp=boothr2_serial_alu_inv_pmos*2 AD=boothr2_serial_alu_inv_pmos+boothr2_serial_alu_inv_pmos+12 \n")
	spice_file.write('.ENDS boothR2_serial_alu')
	spice_file.write("\n")
	#Now Append the List of Transistors
	tran_names_list=[]
	tran_names_list.append("boothr2_serial_alu_inv_pmos")
	#Now Append the List of Wires
	wire_names_list=[]
	return tran_names_list, wire_names_list