import os

def gen_top_pim_opmux_32(name):
    # Create directories
    if not os.path.exists(name):
        os.makedirs(name)
    # Change to directory
    os.chdir(name)  
    
    filename = name + ".sp"
    top_file = open(filename, "w")
    
    top_file.write("\n")
    top_file.write("\n")
    top_file.write("*--------------------------------------------------------------\n")
    top_file.write("* Testbench for alu_serial_unit\n")
    top_file.write("*--------------------------------------------------------------\n")
    top_file.write(".TITLE OpEncoder Unit Testbench\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Include libraries, parameters, and device models\n")
    top_file.write("********************************************************************************\n")
    top_file.write(".LIB \"../includes.l\" INCLUDES\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Simulation setup\n")
    top_file.write("********************************************************************************\n")
    top_file.write("* Run for 40 ns with 10 ps resolution\n")
    top_file.write(".TRAN 1p 5n\n")
    top_file.write(".OPTIONS BRIEF=1\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Power supplies\n")
    top_file.write("********************************************************************************\n")
    top_file.write("VDD n_vdd 0 supply_v\n")
    top_file.write("VSS n_gnd 0 0\n")
    top_file.write("\n")
    top_file.write("VDDD d_vdd 0 supply_v\n")
    top_file.write("VSSD d_gnd 0 0\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Input stimulus\n")
    top_file.write("********************************************************************************\n")
    top_file.write("\n")
    top_file.write("*Bit 2 controls whether it is regular or op\n")
    top_file.write("Vconfig0 conf_0 0 0\n")
    top_file.write("Vconfig1 conf_1 0 0\n")
    top_file.write("Vconfig2 conf_2 0 supply_v\n")
    top_file.write("* Vconfig3 conf_3 0 0\n")
    top_file.write("\n")
    top_file.write("* PULSE(0 supply_v 1n 0 0 2n 4n)\n")
    top_file.write("VNet Net0 0 0\n")
    top_file.write("VA0 A0 0 0\n")
    top_file.write("VA1 A1 0 0\n")
    top_file.write("VA2 A2 0 PULSE(0 supply_v 1n 0 0 2n 4n)\n")
    top_file.write("VA3 A3 0 0\n")
    top_file.write("VA4 A4 0 0\n")
    top_file.write("VA5 A5 0 0\n")
    top_file.write("VA6 A6 0 0\n")
    top_file.write("VA7 A7 0 0\n")
    top_file.write("VA8 A8 0 0\n")
    top_file.write("VA9 A9 0 0\n")
    top_file.write("VA10 A10 0 0\n")
    top_file.write("VA11 A11 0 0\n")
    top_file.write("VA12 A12 0 0\n")
    top_file.write("VA13 A13 0 0\n")
    top_file.write("VA14 A14 0 0\n")
    top_file.write("VA15 A15 0 0\n")
    top_file.write("VA16 A16 0 0\n")
    top_file.write("VA17 A17 0 0\n")
    top_file.write("VA18 A18 0 0\n")
    top_file.write("VA19 A19 0 0\n")
    top_file.write("VA20 A20 0 0\n")
    top_file.write("VA21 A21 0 0\n")
    top_file.write("VA22 A22 0 0\n")
    top_file.write("VA23 A23 0 0\n")
    top_file.write("VA24 A24 0 0\n")
    top_file.write("VA25 A25 0 0\n")
    top_file.write("VA26 A26 0 0\n")
    top_file.write("VA27 A27 0 0\n")
    top_file.write("VA28 A28 0 0\n")
    top_file.write("VA29 A29 0 0\n")
    top_file.write("VA30 A30 0 0\n")
    top_file.write("VA31 A31 0 0\n")
    top_file.write("\n")
    top_file.write("* VA20 A20 0 0\n")
    top_file.write("VB0 B0 0 0\n")
    top_file.write("VB1 B1 0 0\n")
    top_file.write("VB2 B2 0 0\n")
    top_file.write("VB3 B3 0 0\n")
    top_file.write("VB4 B4 0 0\n")
    top_file.write("VB5 B5 0 0\n")
    top_file.write("VB6 B6 0 0\n")
    top_file.write("VB7 B7 0 0\n")
    top_file.write("VB8 B8 0 0\n")
    top_file.write("VB9 B9 0 0\n")
    top_file.write("VB10 B10 0 0\n")
    top_file.write("VB11 B11 0 0\n")
    top_file.write("VB12 B12 0 0\n")
    top_file.write("VB13 B13 0 0\n")
    top_file.write("VB14 B14 0 0\n")
    top_file.write("VB15 B15 0 0\n")
    top_file.write("VB16 B16 0 0\n")
    top_file.write("VB17 B17 0 0\n")
    top_file.write("VB18 B18 0 0\n")
    top_file.write("VB19 B19 0 0\n")
    top_file.write("VB20 B20 0 0\n")
    top_file.write("VB21 B21 0 0\n")
    top_file.write("VB22 B22 0 0\n")
    top_file.write("VB23 B23 0 0\n")
    top_file.write("VB24 B24 0 0\n")
    top_file.write("VB25 B25 0 0\n")
    top_file.write("VB26 B26 0 0\n")
    top_file.write("VB27 B27 0 0\n")
    top_file.write("VB28 B28 0 0\n")
    top_file.write("VB29 B29 0 0\n")
    top_file.write("VB30 B30 0 0\n")
    top_file.write("VB31 B31 0 0\n")
    top_file.write("\n")
    top_file.write("* .param nand2_pim_opmux_comb_32_nmos=88n\n")
    top_file.write("* .param nand2_pim_opmux_comb_32_pmos=44n\n")
    top_file.write("\n")
    top_file.write("* .param nand3_pim_opmux_comb_32_nmos=132n\n")
    top_file.write("* .param nand3_pim_opmux_comb_32_pmos=88n\n")
    top_file.write("\n")
    top_file.write("* .param inv_pim_opmux_comb_32_nmos=44n\n")
    top_file.write("* .param inv_pim_opmux_comb_32_pmos=44n\n")
    top_file.write("\n")
    top_file.write("* .param nor2_pim_opmux_comb_32_nmos=44n\n")
    top_file.write("* .param nor2_pim_opmux_comb_32_pmos=176n\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Circuit under test\n")
    top_file.write("********************************************************************************\n")
    top_file.write("\n")
    top_file.write("Xpim_opmux_comb_32 A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 A10 A11 A12 A13 A14 A15 A16 A17 A18 A19 A20 A21 A22 A23 A24 A25 A26 A27 A28 A29 A30 A31 \n")
    top_file.write("+ B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 B10 B11 B12 B13 B14 B15 B16 B17 B18 B19 B20 B21 B22 B23 B24 B25 B26 B27 B28 B29 B30 B31 \n")
    top_file.write("+Net0 \n")
    top_file.write("+conf_0 conf_1 conf_2 \n")
    top_file.write("+opnX_bus0 opnX_bus1 opnX_bus2 opnX_bus3 opnX_bus4 opnX_bus5 opnX_bus6 opnX_bus7 opnX_bus8 opnX_bus9 opnX_bus10 opnX_bus11 opnX_bus12 opnX_bus13 opnX_bus14 opnX_bus15 opnX_bus16 opnX_bus17 opnX_bus18 opnX_bus19 opnX_bus20 opnX_bus21 opnX_bus22 opnX_bus23 opnX_bus24 opnX_bus25 opnX_bus26 opnX_bus27 opnX_bus28 opnX_bus29 opnX_bus30 opnX_bus31 opnY_bus0 opnY_bus1 opnY_bus2 opnY_bus3 opnY_bus4 opnY_bus5 opnY_bus6 opnY_bus7 opnY_bus8 opnY_bus9 opnY_bus10 opnY_bus11 opnY_bus12 opnY_bus13 opnY_bus14 opnY_bus15 opnY_bus16 opnY_bus17 opnY_bus18 opnY_bus19 opnY_bus20 opnY_bus21 opnY_bus22 opnY_bus23 opnY_bus24 opnY_bus25 opnY_bus26 opnY_bus27 opnY_bus28 opnY_bus29 opnY_bus30 opnY_bus31 n_vdd n_gnd pim_opmux_comb\n")
    # top_file.write("\n")
    # top_file.write("Xdummyinv x inv_out d_vdd d_gnd inv Wn=inv_pim_opmux_comb_32_nmos Wp=inv_pim_opmux_comb_32_pmos\n")
    # top_file.write("Xdummynand2 x nand2_out d_vdd d_gnd nand2 Wn=nand2_pim_opmux_comb_32_nmos Wp=nand2_pim_opmux_comb_32_pmos\n")
    # top_file.write("Xdummynand3 x nand3_out d_vdd d_gnd nand3 Wn=nand3_pim_opmux_comb_32_nmos Wp=nand3_pim_opmux_comb_32_pmos\n")
    # top_file.write("Xdummynor2 x x nor2_out d_vdd d_gnd nor2_decode Wn=nor2_pim_opmux_comb_32_nmos Wp=nor2_pim_opmux_comb_32_pmos\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write("** Measurements\n")
    top_file.write("********************************************************************************\n")
    top_file.write("*X measurements inv\n")
    top_file.write("*Inverted measurements\n")

    top_file.write(".MEASURE TRAN meas_"+name+"_trise TRIG V(A2) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     FROM=1n TO=6n\n")
    top_file.write(".MEASURE TRAN meas_"+name+"_tfall TRIG V(A2) VAL='supply_v/2' FALL=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' FALL=1\n")
    top_file.write("\n")
    top_file.write(".MEASURE TRAN meas_total_trise TRIG V(A2) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     FROM=1n TO=6n\n")
    top_file.write(".MEASURE TRAN meas_total_tfall TRIG V(A2) VAL='supply_v/2' FALL=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' FALL=1\n")
    top_file.write("\n")

    top_file.write(".MEASURE TRAN tpd_rise TRIG V(A2) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' RISE=1\n")
    top_file.write("+     FROM=1n TO=6n\n")
    top_file.write(".MEASURE TRAN tpd_fall TRIG V(A2) VAL='supply_v/2' FALL=1\n")
    top_file.write("+     TARG V(opnY_bus0) VAL='supply_v/2' FALL=1\n")
    top_file.write("\n")
    # top_file.write("* *inverter\n")
    # top_file.write(".MEASURE TRAN tpd_inv_rise TRIG V(x) VAL='supply_v/2' FALL=1\n")
    # top_file.write("+     TARG V(inv_out) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     FROM=1n TO=6n\n")
    # top_file.write(".MEASURE TRAN tpd_inv_fall TRIG V(x) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     TARG V(inv_out) VAL='supply_v/2' FALL=1\n")
    # top_file.write("*nand2\n")
    # top_file.write(".MEASURE TRAN tpd_nand2_rise TRIG V(x) VAL='supply_v/2' FALL=1\n")
    # top_file.write("+     TARG V(nand2_out) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     FROM=1n TO=6n\n")
    # top_file.write(".MEASURE TRAN tpd_nand2_fall TRIG V(x) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     TARG V(nand2_out) VAL='supply_v/2' FALL=1\n")
    # top_file.write("*nand3\n")
    # top_file.write(".MEASURE TRAN tpd_nand3_rise TRIG V(x) VAL='supply_v/2' FALL=1\n")
    # top_file.write("+     TARG V(nand3_out) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     FROM=1n TO=6n\n")
    # top_file.write(".MEASURE TRAN tpd_nand3_fall TRIG V(x) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     TARG V(nand3_out) VAL='supply_v/2' FALL=1\n")
    # top_file.write("*nor2\n")
    # top_file.write(".MEASURE TRAN tpd_nor2_rise TRIG V(x) VAL='supply_v/2' FALL=1\n")
    # top_file.write("+     TARG V(nor2_out) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     FROM=1n TO=6n\n")
    # top_file.write(".MEASURE TRAN tpd_nor2_fall TRIG V(x) VAL='supply_v/2' RISE=1\n")
    # top_file.write("+     TARG V(nor2_out) VAL='supply_v/2' FALL=1\n")
    # top_file.write("\n")
    top_file.write("* Logic levels at output\n")
    top_file.write("* .MEASURE TRAN vout_high  FIND V(opnY_bus0) AT=2n\n")
    top_file.write(".MEASURE TRAN meas_logic_low_voltage FIND V(opnY_bus0) AT=4n\n")
    top_file.write("\n")
    top_file.write("* Power consumption\n")
    top_file.write(".MEASURE TRAN i_vdd      INTEGRAL I(VDD) FROM=0n TO=5n\n")
    top_file.write(".MEASURE TRAN meas_avg_power  PARAM = '-(i_vdd/5n)*supply_v'\n")
    top_file.write("\n")
    top_file.write("********************************************************************************\n")
    top_file.write(".OPTION POST\n")
    top_file.write("\n")
    top_file.write(".END\n")
    top_file.write(".END")
    top_file.close()
